### ISSUE TITLE
Value Error

### ISSUE THREAD

**Issue by ghost** [tobiaspc/wofi-scripts#1]
thanks for this great script! 

it i tried running it but it return an error:

```
Traceback (most recent call last):
  File "windows.py", line 91, in <module>
    selected_id = parse_id(windows, selected)
  File "windows.py", line 70, in parse_id
    selected = int(selected.decode("UTF-8"))
ValueError: invalid literal for int() with base 10: 'Title\n'
```

Works for me with some small changes, thought i'd share
https://github.com/trashcan55/wofi-scripts/commit/c1b0a0564968082bcfa2b083b12f60ea7d2cb9e5

(I learned python just about a month ago so probably it's not the most elegant fix)

**Comment by tobiaspc** [comment]
Could you please send me the output of `swaymsg -t get_tree` and `sway -v`?

With your changes, the script no longer works for me (Arch Linux, sway 1.4):

    Traceback (most recent call last):
      File "./windows.py", line 93, in <module>
        selected_id = parse_id(windows, parsed_windows, selected)
      File "./windows.py", line 72, in parse_id
        getindex = int(parsed_windows.index(selected))
    ValueError: '0' is not in list

**Comment by ghost** [comment]
That's weird. I have sway v1.4 installed on manjaro, should be the same binary :thinking: 

<details>
<summary>swaymsg -t get_tree</summary>

```
{
  "id": 1,
  "name": "root",
  "rect": {
    "x": 0,
    "y": 0,
    "width": 1366,
    "height": 768
  },
  "focused": false,
  "focus": [
    3
  ],
  "border": "none",
  "current_border_width": 0,
  "layout": "splith",
  "orientation": "horizontal",
  "percent": null,
  "window_rect": {
    "x": 0,
    "y": 0,
    "width": 0,
    "height": 0
  },
  "deco_rect": {
    "x": 0,
    "y": 0,
    "width": 0,
    "height": 0
  },
  "geometry": {
    "x": 0,
    "y": 0,
    "width": 0,
    "height": 0
  },
  "window": null,
  "urgent": false,
  "floating_nodes": [
  ],
  "sticky": false,
  "type": "root",
  "nodes": [
    {
      "id": 2147483647,
      "name": "__i3",
      "rect": {
        "x": 0,
        "y": 0,
        "width": 1366,
        "height": 768
      },
      "focused": false,
      "focus": [
        2147483646
      ],
      "border": "none",
      "current_border_width": 0,
      "layout": "output",
      "orientation": "horizontal",
      "percent": null,
      "window_rect": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "deco_rect": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "geometry": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "window": null,
      "urgent": false,
      "floating_nodes": [
      ],
      "sticky": false,
      "type": "output",
      "nodes": [
        {
          "id": 2147483646,
          "name": "__i3_scratch",
          "rect": {
            "x": 0,
            "y": 0,
            "width": 1366,
            "height": 768
          },
          "focused": false,
          "focus": [
          ],
          "border": "none",
          "current_border_width": 0,
          "layout": "splith",
          "orientation": "horizontal",
          "percent": null,
          "window_rect": {
            "x": 0,
            "y": 0,
            "width": 0,
            "height": 0
          },
          "deco_rect": {
            "x": 0,
            "y": 0,
            "width": 0,
            "height": 0
          },
          "geometry": {
            "x": 0,
            "y": 0,
            "width": 0,
            "height": 0
          },
          "window": null,
          "urgent": false,
          "floating_nodes": [
          ],
          "sticky": false,
          "type": "workspace"
        }
      ]
    },
    {
      "id": 3,
      "name": "LVDS-1",
      "rect": {
        "x": 0,
        "y": 0,
        "width": 1366,
        "height": 768
      },
      "focused": false,
      "focus": [
        49,
        8
      ],
      "border": "none",
      "current_border_width": 0,
      "layout": "output",
      "orientation": "none",
      "percent": 1.0,
      "window_rect": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "deco_rect": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "geometry": {
        "x": 0,
        "y": 0,
        "width": 0,
        "height": 0
      },
      "window": null,
      "urgent": false,
      "floating_nodes": [
      ],
      "sticky": false,
      "type": "output",
      "active": true,
      "dpms": true,
      "primary": false,
      "make": "Unknown",
      "model": "0x02D3",
      "serial": "0x00000000",
      "scale": 1.0,
      "scale_filter": "nearest",
      "transform": "normal",
      "current_workspace": "4",
      "modes": [
        {
          "width": 1366,
          "height": 768,
          "refresh": 60002
        }
      ],
      "current_mode": {
        "width": 1366,
        "height": 768,
        "refresh": 60002
      },
      "max_render_time": 0,
      "nodes": [
        {
          "id": 49,
          "name": "4",
          "rect": {
            "x": 6,
            "y": 34,
            "width": 1354,
            "height": 728
          },
          "focused": false,
          "focus": [
            50,
            48
          ],
          "border": "none",
          "current_border_width": 0,
          "layout": "stacked",
          "orientation": "none",
          "percent": null,
          "window_rect": {
            "x": 0,
            "y": 0,
            "width": 0,
            "height": 0
          },
          "deco_rect": {
            "x": 0,
            "y": 0,
            "width": 0,
            "height": 0
          },
          "geometry": {
            "x": 0,
            "y": 0,
            "width": 0,
            "height": 0
          },
          "window": null,
          "urgent": false,
          "floating_nodes": [
          ],
          "sticky": false,
          "num": 4,
          "output": "LVDS-1",
          "type": "workspace",
          "representation": "S[firefox gnome-terminal-server]",
          "nodes": [
            {
              "id": 48,
              "name": "Value Error · Issue #1 · tobiaspc\/wofi-scripts - Mozilla Firefox",
              "rect": {
                "x": 6,
                "y": 88,
                "width": 1354,
                "height": 674
              },
              "focused": false,
              "focus": [
              ],
              "border": "pixel",
              "current_border_width": 1,
              "layout": "none",
              "orientation": "none",
              "percent": 1.0,
              "window_rect": {
                "x": 0,
                "y": 1,
                "width": 1354,
                "height": 674
              },
              "deco_rect": {
                "x": 0,
                "y": 0,
                "width": 1354,
                "height": 27
              },
              "geometry": {
                "x": 0,
                "y": 0,
                "width": 600,
                "height": 701
              },
              "window": null,
              "urgent": false,
              "floating_nodes": [
              ],
              "sticky": false,
              "type": "con",
              "fullscreen_mode": 0,
              "pid": 11517,
              "app_id": "firefox",
              "visible": false,
              "marks": [
              ],
              "max_render_time": 0,
              "nodes": [
              ]
            },
            {
              "id": 50,
              "name": "user@host: ~",
              "rect": {
                "x": 6,
                "y": 88,
                "width": 1354,
                "height": 674
              },
              "focused": true,
              "focus": [
              ],
              "border": "pixel",
              "current_border_width": 1,
              "layout": "none",
              "orientation": "none",
              "percent": 1.0,
              "window_rect": {
                "x": 0,
                "y": 1,
                "width": 1354,
                "height": 674
              },
              "deco_rect": {
                "x": 0,
                "y": 27,
                "width": 1354,
                "height": 27
              },
              "geometry": {
                "x": 0,
                "y": 0,
                "width": 732,
                "height": 444
              },
              "window": null,
              "urgent": false,
              "floating_nodes": [
              ],
              "sticky": false,
              "type": "con",
              "fullscreen_mode": 0,
              "pid": 1952,
              "app_id": "gnome-terminal-server",
              "visible": true,
              "marks": [
              ],
              "max_render_time": 0,
              "nodes": [
              ]
            }
          ]
        },
        {
          "id": 8,
          "name": "6",
          "rect": {
            "x": 6,
            "y": 34,
            "width": 1354,
            "height": 728
          },
          "focused": false,
          "focus": [
            7
          ],
          "border": "none",
          "current_border_width": 0,
          "layout": "stacked",
          "orientation": "none",
          "percent": null,
          "window_rect": {
            "x": 0,
            "y": 0,
            "width": 0,
            "height": 0
          },
          "deco_rect": {
            "x": 0,
            "y": 0,
            "width": 0,
            "height": 0
          },
          "geometry": {
            "x": 0,
            "y": 0,
            "width": 0,
            "height": 0
          },
          "window": null,
          "urgent": false,
          "floating_nodes": [
          ],
          "sticky": false,
          "num": 6,
          "output": "LVDS-1",
          "type": "workspace",
          "representation": "S[gnome-terminal-server]",
          "nodes": [
            {
              "id": 7,
              "name": "Gomuks",
              "rect": {
                "x": 6,
                "y": 61,
                "width": 1354,
                "height": 701
              },
              "focused": false,
              "focus": [
              ],
              "border": "pixel",
              "current_border_width": 1,
              "layout": "none",
              "orientation": "none",
              "percent": 1.0,
              "window_rect": {
                "x": 0,
                "y": 1,
                "width": 1354,
                "height": 728
              },
              "deco_rect": {
                "x": 0,
                "y": 0,
                "width": 1354,
                "height": 27
              },
              "geometry": {
                "x": 0,
                "y": 0,
                "width": 732,
                "height": 444
              },
              "window": null,
              "urgent": false,
              "floating_nodes": [
              ],
              "sticky": false,
              "type": "con",
              "fullscreen_mode": 0,
              "pid": 1952,
              "app_id": "gnome-terminal-server",
              "visible": false,
              "marks": [
              ],
              "max_render_time": 0,
              "nodes": [
              ]
            }
          ]
        }
      ]
    }
  ]
}
```

</details>

**Comment by tobiaspc** [comment]
Even more weirdness:

Your `get_tree` output works with my version (I just parsed it instead of parsing swaymsg's output)  and fails with your changes...

What python version do you use? 3.8.3 here.

**Comment by ghost** [comment]
also using 3.8.3 :upside_down_face: 

I'm not sure if I understand correctly what is happening inside `switch_window(id)`, but since it keeps returning a string instead of a numeral maybe the difference lies in the shell, not python?

anyway since you script works fine and my changes work for me, i guess i'll just leave it like that and hope it doesn't break at some point 😅

**Comment by tobiaspc** [comment]
FYI: I merged your changes after locating the issue: a config option for wofi that I had set before and forgot about.
